### ISSUE TITLE
Arm64 docker image are not working, because they contain a x64 binary

### ISSUE THREAD

**Issue by holomekc** [karlderkaefer/cdk-notifier#160]
Hi,

it looks like that you build the binary once on a ubuntu machine and then push the docker image for both platforms. This results in the issue:

```
exec /bin/cdk-notifier: exec format error
```

The release in GitHub itself looks fine though.

**Comment by karlderkaefer** [comment]
Thanks for report I will check today

**Comment by karlderkaefer** [comment]
the issue is explaining [here](https://github.com/docker/buildx/discussions/1382#discussioncomment-6252049) It's probably the cache. Either I remove cache or I use matrix build to build every docker image on separate platform or I check again the [cross-compile multi-platform docker guide](https://www.docker.com/blog/faster-multi-platform-builds-dockerfile-cross-compilation-guide/)

**Comment by karlderkaefer** [comment]
@holomekc please can you verify and let me know if it's working? I currently have no arm64 at hand just tested on emulated environment 
`docker run --rm  karlderkaefer/cdk-notifier:2.12.4 --help`

**Comment by holomekc** [comment]
Hi @karlderkaefer,

thx for the quick fix. Yes it works fine now!
