### ISSUE TITLE
Feature request: Include a <details> tag around the comment body so it's foldable

### ISSUE THREAD

**Issue by fermezz** [karlderkaefer/cdk-notifier#76]
In markdown, the [`<details>` tag can be used to fold and unfold content](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/organizing-information-with-collapsed-sections). That would make the comment much cleaner as CDK diff's outputs tend to be very verbose.

**Comment by karlderkaefer** [comment]
I remember I wanted to used collapsed, but it was not possible to combine it with diff output. It seems it is possible nowadays, I will check next weekend how to integrate. Since it it's only supported for GitHub as far as I can see. I agree, that would be much cleaner
<details><summary>CLICK ME</summary>
<p>

#### We can hide anything, even code!

```diff
diff --git a/diff_test.txt b/diff_test.txt
index 6b0c6cf..b37e70a 100644
--- a/diff_test.txt
+++ b/diff_test.txt
@@ -1 +1 @@
-this is a git diff test example
+this is a diff example
```
</p>
</details>

**Comment by fermezz** [comment]
@karlderkaefer any chance you were able to take a look? I can try to make a pr myself if you point me in the right direction. I don't mean to push, I just want to propose to use this library in my company but they like pr-cleanliness very much 😓

**Comment by karlderkaefer** [comment]
@fermezz I totally understand. I did have some busy days, practically no time to continue, I'm aiming to release new version on Wednesday. If there is any more delay, I will let you know and give you some hints how to implement

**Comment by karlderkaefer** [comment]
@fermezz let me know if the feature is as expected or if anything is missing
